### ISSUE TITLE
The XmlReader state should be Interactive

### ISSUE THREAD

**Issue by seldary** [marek-stoj/NReadability#10]
When trying to transcode the url: http://www.ad120.co.il/ it fails with:

System.InvalidOperationException occurred
  Message=The XmlReader state should be Interactive.
  Source=System.Xml.Linq
  StackTrace:
       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
       at System.Xml.Linq.XDocument.Load(XmlReader reader)
       at NReadability.SgmlDomBuilder.LoadDocument(String htmlContent) in D:\Development\ExternalLibrary\NReadability\Src\NReadability\NReadability\SgmlDomBuilder.cs:line 105
  InnerException: 

It happens on many other non-english pages (namely hebrew & russian).

**Comment by marek-stoj** [comment]
Sorry, but I don't have time to investigate this as it's clearly the problem with SgmlReader. Maybe you could contact developers of SgmlReader: https://github.com/mindtouch/sgmlreader.
